### ISSUE TITLE
Possibility to define dead zones for thrusters / analog mouse hat

### ISSUE THREAD

**Issue by Berndserk** [Aussiedroid/AD-EDWarthogEnhancedScript#10]
Hi,

it would be great if the analog mouse hat used for thrusters could have dead zones defined.
Currently they have zero and moving the mouse hat in one direction (e.g. vertical) always applies at least some thrust to the other direction (e.g. lateral) which is quite impractiable for FA OFF maneuvers.

regards
Bernd

**Comment by Aussiedroid** [comment]
Hey Bernd,

That is a good idea! A short time back I had upgraded my nub to a stick too and could probably use this functionality myself. As I mentioned in my other reply, I don't have my hardware setup currently to do any testing/playing, but will mark this down to look into before the next script release.

Cheers, AD

**Comment by Berndserk** [comment]
Hi, that sounds great, thx! Btw: What did you mean by "upgraded my nub to a stick"?
Another Problem i face is due to the fact that i don't have rudder pedals i put roll and pitch on the stick and have yaw therefor on the digital switch next to the mouse hat, but this makes maneuvers like yaw plus lateral input very hard, and sometimes causes me to accidentally boost *facepalm*. I was thinking of a little remap but so far no better solution came to my mind.

**Comment by Aussiedroid** [comment]
Oh, I mean the modification sold over [here](https://deltasimelectronics.com/products/thumbstick-slew-sensor-adapter). I now have an analog thumbstick like on a game controller instead of the nub/nipple. Haven't used it much yet, but does work well. Still probably not a real substitution for some rudder pedals but better than the default. More precise. 

Remap is tough given the lack of alternative axis options, but you could look into the alternative flight control mappings in game to double up the use on some axes. Believe you would hold or toggle the alternative flight mapping controls, and you could swap say your roll with yaw temporarily or other combos. Still might be a bit limited if wanting to use all 3 axes at once.

Took another look into the code today and also noticed that I do already set a curve for the Slew Axes. See AD_EDHardware (Line # ~93):

		MapAxis(&Throttle, SCX, DX_XROT_AXIS, AXIS_NORMAL, MAP_ABSOLUTE);						// Set Slew Control X Axis
			SetSCurve(&Throttle, SCX, 0, 20, 0, 2, -1);
		MapAxis(&Throttle, SCY, DX_YROT_AXIS, AXIS_NORMAL, MAP_ABSOLUTE);						// Set Slew Control Y Axis
			SetSCurve(&Throttle, SCY, 0, 20, 0, 2, -1);

If you want to set a different deadzone you should be able to change the '20' value in each SetSCurve to another value. I'll update this in the next version to a user preference for easy editing though. 

Cheers, AD

**Comment by Berndserk** [comment]
Awesome... I will try this today on a few Cargotrips :-D Also thx for the link... I think I am in urgent need of this now :-D

**Comment by Aussiedroid** [comment]
Hey Bernd,

How did it go with changing the Slew Deadzone? Any success? :)

Cheers, AD

**Comment by Berndserk** [comment]
Hey,

sorry for the late reply. To be honest i was not really able to test this properly since there seems to be a default deadzone of 20% already from what i understood? This made me wondering and i tried with the default, but i need more practice because this mouse hat in general behaves somewhat strange so i cannot tell if there is a proper dead zone for me :-). Anyway dog fighting with slew thrusters is not so good. I hope the analog stick you replaced it with is much better. Currently my FA OFF manoeuvers suck a bit :-D but i will test the parameters to change it today on a cargo flight :-D

**Comment by Aussiedroid** [comment]
Hey thanks for getting back to me.

The default deadzone is just one I set in the profile, but you should be able to change this to any value 0-100 using the suggested code update. In theory anyways :) Just wanted to see if it helped, but I will test it out more once I get back up and going. If you do play around and test things out, I am always happy to hear your feedback :)

Cheers, AD
