### ISSUE TITLE
Missing devices: ThrustMasterWarthogJoystick

### ISSUE THREAD

**Issue by DickThomas** [Aussiedroid/AD-EDWarthogEnhancedScript#11]
Hi

Since the last update sometime around13/06/2020
when I start Elite Dangerous with your profile ED:HZ nolonger detects the HOTAS.

the file ```BindingLoadingErrors``` says the following
```
There where errors when loading preset file: Aussiedroid Warthog Enhanced 4.2.1.3.0.binds
There are multiple entries of binding "MouseGUI" Only the first will be used
There are multiple entries of binding "MouseGUI" Only the first will be used
Missing devices: ThrustMasterWarthogJoystick
```

I'm using Windows 10
latest thrustmaster drivers and TARGET software as I only reinstalled windows10 a week ago 👎 

not sure what else can I say.
[BindingLoadingErrors.log](https://github.com/Aussiedroid/AD-EDWarthogEnhancedScript/files/4775016/BindingLoadingErrors.log)

**Comment by Aussiedroid** [comment]
Hey Dick,

Thanks for the report. I have been playing around with a new version of the script over the last day but have not seen that error directly myself (although I did need to do a full reinstall drivers & software post Windows updates it seems). 

From the errors being returned, to me it seems to be suggesting duplication of mappings, missing devices which may indicate that the script is not loaded correctly. I assume the script is still running without failing though, so that may suggest instead that it has failed in the past and now the binding file is corrupt, or you may have had a device drop out once the script was running which could also cause binding issues depending how you exited the game. It is hard to say though. 

I would recommend checking your Game Controller device list (search USB Controllers in Search bar in Windows to find) in Windows and check the order of the devices connected and that all devices are seen. It should show Joystick then Throttle then any other devices, ie should be at the top of the list. If it is not then you may need to unplug all devices, shut down then just plug the HOTAS back in and run script. Different USB ports/hub can sometimes be a simple solution too when the combined device doesnt create successfully.

If that all looks fine, I would then try a brand new copy of the script and binding files from download or backup. Delete or make copy of the existing ones to remove them from the bindings folder and retest. With the script running I would wait a while and test out in Device Analyzer and confirm the combined device is present, and that using the buttons/toggles/axes do not crash the script. If that holds up over an extended test, start ED again and open your fresh copy of the bindings and let us know how it goes.

Another alternative you can try is the latest beta 4.3.0 build I have uploaded last night. Its still a work in progress and will be updated further but I know I have run these in the latest ED build just 12 hours ago and working fine.

If none of that work, if you can share your hardware setup if you run anything else than the HOTAS or other 3rd party software and see if we can narrow down what is going on. :)

Cheers, AD

**Comment by DickThomas** [comment]
Greetings, CMD AD
I've seem to have "fixed it" i created a new profile by going to generic joystick and saving one axis 
e.g  Roll to the joystick. and just one axis was fine
Then saved this as custom, restarted the game and your profile was there.
I hope this is of help to over Commanders
if this isn't "the fix" I'm more than happy to tinker more
I've attached the bindings folder
Fly Safe o7



[Bindings.zip](https://github.com/Aussiedroid/AD-EDWarthogEnhancedScript/files/4775920/Bindings.zip)

**Comment by Aussiedroid** [comment]
Cool! Glad it is sorted out. Appreciate you sharing what fixed it incase it happens to others too :)
