### ISSUE TITLE
No v4.3.0 release available

### ISSUE THREAD

**Issue by barlevalon** [Aussiedroid/AD-EDWarthogEnhancedScript#12]
Not sure if this is intentional, but the "LATEST BUILD | v4.3.0" link in the [readme ](https://github.com/Aussiedroid/AD-EDWarthogEnhancedScript#latest-build--v430--updated-for-elite-dangerous--beyond-37--fleet-carrier-update) goes to the releases page, where the latest release is 4.2.1

**Comment by Aussiedroid** [comment]
Hey barlevalon,

It's intentional :) .. I haven't had a chance to properly test the beta build yet, so I haven't updated the release at this stage. Sorry for any confusion.

4.3.0 should be fine from some earlier testing so hopefully will release next weekend (if I get some time to play this week) :)

Cheers, AD

**Comment by barlevalon** [comment]
Awesome, will await it patiently :)
