### ISSUE TITLE
Changing HUD Mode whilst in SRV toggles handbrake

### ISSUE THREAD

**Issue by ClickerNZ** [Aussiedroid/AD-EDWarthogEnhancedScript#14]
Hiya,

Issue (per issue title) reported on forum by CMDR Farodin Angels on November 5, 2020.

Bind file (Lines 874-880):

AutoBreakBuggyButton
	Primary Device="ThrustMasterWarthogCombined" Key="Joy_4" /
	Secondary Device="Keyboard" Key="Key_Minus"
		Modifier Device="Keyboard" Key="Key_LeftControl" /
	/Secondary
	ToggleOn Value="1" /
/AutoBreakBuggyButton

Suggest remove Primary Device binding.

Cheers
Clicker

**Comment by Aussiedroid** [comment]
Hey Clicker,

Thanks for sharing the report (haven't been across the forums for a while so its appreciated!). Still check here every couple of weeks though.

The same behaviour can be seen if using the 'Change Game Modes' macro as well unless timed perfectly. Not a deal breaker in that scenario as you are exiting to main menu.

I'll see if I can replicate this and look at alternatives/improvements as per your suggestion.

From memory, it does toggle the handbrake (as noted by the sound/UI) when switching modes, but since its quick it should not result in much movement. I've just been living with it since I personally like the handbrake on the pinky modifier. Should not happen but as one is programmed in the script and the other direct in the bindings both fire.

Cheers mate,
AD

**Comment by Aussiedroid** [comment]
Ok a temporary solution for now. I can't seem to get it to work the way I want on the pinky trigger without triggering the double tap. So instead I have moved it to the China Hat (back) for the next version.

Remove the Joy 4 mapping on SRV Handbrake in the bindings, and update script as per below. This will map to both CruiseOnThrottle user preferences coupling with the next in route.

```
[AD_ED_v4.x.x.tmc - line 380:]

	// CRUISE ON THROTTLE CONFIG //
	if(CruiseOnThrottle == 0) {											// Sets China Hat to add Frame Shift Drive when Cruise on Throttle is disabled.
		MapKey(&Throttle,  CHF, TEMPO(FrameShiftDrive, Supercruise, LongPressDelay)); 		        	// China Hat FORWARD [When Route Blocked HOLD for Supercruise]
		MapKey(&Throttle,  CHB, TEMPO(EXEC(									// China Hat BACK 	 [Short: Night Vision or Orbital Lines(+Pinky), Very Long: Next Sys Route]
					"if(Joystick[S4])  ActKey(KEYON+PULSE+OrbitalLines);"
					"if(!Joystick[S4]) initNightVisionEnhancer(1);"),
				     EXEC(
					"if(!Joystick[S4]) ActKey(KEYON+PULSE+mChinaHatBack);"), LongPressDelay)); }
	if(CruiseOnThrottle == 1) {											// Sets China Hat to remove Frame Shift Drive when Cruise on Throttle is enabled.
		MapKey(&Throttle,  CHF, EXEC(										// China Hat FORWARD
					"if(Joystick[S4])  ActKey(KEYON+PULSE+OrbitalLines);"
					"else			   initNightVisionEnhancer(1);"));
		MapKey(&Throttle,  CHB, mChinaHatBack);	}								// China Hat BACK



[AD_EDMacros_v4.x.x - line 204:]

        int mChinaHatBack;

	mChinaHatBack = CHAIN(												// MACRO: China Hat Back Keybinding Combo (See: CRUISE ON THROTTLE CONFIG in AD_ED_v4.x.x.tmc)
		PULSE+SelectNextSystemInRoute,  D(),									//  Combines mutually exclusive bindings SRV Handbrake & Next System In Route to a single toggle
		PULSE+SRVHandbrake);

```

Cheers, AD
