### ISSUE TITLE
I have a bit of a weird, and perhaps difficult request

### ISSUE THREAD

**Issue by six-shooter** [Aussiedroid/AD-EDWarthogEnhancedScript#15]
I would love a version of this with just the lights and coupled switches. where I can just bind all the rest by myself. 
I don't need a lot of the options currently available, but would love to use those buttons for other stuff, as an example: I'd love to use the two-way-switch on the left of the throttle for my lights/nightvision, but I can't bind them in the game, same goes for some other switches that normally do things in your script, like the autopilot-engage button that I'd love to use for the FSD.

Things I would like to keep are: 
-The status-lights and switches that are coupled 
-the forward-only flapswitch

Got any tips?

**Comment by Aussiedroid** [comment]
Hey six-shooter,

Thanks for checking out the script!

From what you are describing, it would require a complete rewrite of the script. Essentially a stripped down version to allow you to program it all yourself using the functions/macros etc. Not something I will be looking to include in future versions, as it becomes more complicated maintaining multiple versions, especially when doing updates and doing testing etc.

Depending how much time you wish to dedicate to it, and how familiar you are with the scripting language, I think the best option would be to keep the core file structure as per the download pack, but then clear the mapped commands in the main AD_ED_4.3.0.tmc file (primarily between the lines 150-500). These are the ones that map the buttons/axes/toggles into ED. It would mean some of the code in the other files will no longer be used, but would be no issues leaving it in as would still compile.

Then once cleared the mappings, you can remap any you wish to use in the script and map the rest directly in ED via the config binding file depending how you wish to set it up (just make sure keybinds align to what is also mapped in the script). Obviously, it would also require clearing & aligning the mappings in the binding file too to match your changes and make sure the bindings work fine with the updated script running.

The alternative, would be to use a default/basic script and just add the code you want from my script. I always welcome people to reuse the code for their own purposes so would have no objection to you 'borrowing' anything you find useful. :)

The main code for the LED stuff is found in the 'initLEDController' function in the AD_EDFunctions file, but there is also a few bits here and there for specific mappings (such as Nightvision), but most should be in the functions file.

Also to add, the flap switch on the throttle can be remapped via the user preferences if you do not need the ability to change throttle presets. Likewise, the Autopilot button can be customised too via the user preferences. Those may help you in the short term.

Hope it helps, but if you have any specific questions I am happy to help further if I can. Normally best to catch me across on Steam these days, but I do check back here every few weeks otherwise.

Cheers, AD
