### ISSUE TITLE
UserPIPPref set to 2, short tap does SYSx4, WEPx2 instead of SYSx4, ENGx2

### ISSUE THREAD

**Issue by himmelweiss** [Aussiedroid/AD-EDWarthogEnhancedScript#17]
If i set UserPIPPref to 2 the left short tap sets the pips to SYSx4, WEPx2 instead of SYSx4, ENGx2 like shown on the preview joystick images.

How can i swap it?

If UserPIPPref is set to 3 everything works as described on your joystick preview images.
However i prefer short taps only so that's why i kinda need UserPIPPref set to 2.

**Comment by Aussiedroid** [comment]
Hi @himmelweiss,

Thanks for reporting your issue. 

I've just had a look at the code in the AD_ED_Vxxx.tmc file and it appears that the correct mapping I have set up is SYSx4, WEPx2 when UserPIPPref 2 is chosen (this is my usual personal preference too). I believe I have changed this at some point in the past from ENGx2 variant, but forgot to update the reference maps & swap the the UserPIPPref 3 variation too to align. Sorry for the confusion.

I'll look to update the reference maps for my next release to make sure it aligns to the script & change the UserPIPPref 3 to swap the Medium and Long mappings. Could really map it either way depending on your focus in game, but for now I will leave it as WEP as the default.

That said, if you would prefer to set your own combinations or change it back to ENGx2, you can do this pretty easily in the AD_ED file around line 279-298  (if(UserPIPPref == 2)). 

For example, to change the left direction back to ENGx2 instead of WEPx2 you would change line 291 to:

`EXEC("if(!Joystick[S4]) initPIPMapper(SYS,ENG);"				// [Long: 4xSYS 2xENG]`

Let me know if you have any questions or concerns. :)

Hope it helps,
AD

**Comment by himmelweiss** [comment]
Changed and works like a charm, thanks!

Needed SYSx4, ENGx2 for thargoid interceptors. 
Maybe at some point i will try to get used to short & long taps, would give me more options.

Your script is simply the best, thanks for all your hard work!

**Comment by Aussiedroid** [comment]
Thanks a lot!

Glad to help.

Fly Safe CMDR.
